# Use postgres/example user/password credentials
version: '3.1'

services:
# https://hub.docker.com/_/postgres
# https://github.com/cookiecutter/cookiecutter-django
# https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html
  postgres:
    image: postgres:15
    container_name: drf-ejercicio1
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - djres-ejercicio1_data:/var/lib/postgresql/data
      #- djres-tutorial_data_backups:/backups
    ports:
      - 5432:5432

volumes:
  djres-ejercicio1_data:
  # djres-tutorial_data_backups:


